# Generated by Django 4.2.3 on 2023-08-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('mainColor', models.CharField(max_length=20, null=True)),
                ('subColor', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
